// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2fy3cQW8LpyTlKaqhMU5x1R-rFCYnCi0',
    appId: '1:845609438124:android:51b222685056f54ad1c809',
    messagingSenderId: '845609438124',
    projectId: 'challenge1-385f2',
    storageBucket: 'challenge1-385f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvFdB63gwuGN2dtim7V5UYAXIRs6mLvu8',
    appId: '1:845609438124:ios:ffb2e89f3a26bb19d1c809',
    messagingSenderId: '845609438124',
    projectId: 'challenge1-385f2',
    storageBucket: 'challenge1-385f2.firebasestorage.app',
    androidClientId: '845609438124-m9enmgjm1botqmuo8supg45pcqilqdu8.apps.googleusercontent.com',
    iosClientId: '845609438124-tjl7rsaulv9p79d8mbm68n0skokq3ce0.apps.googleusercontent.com',
    iosBundleId: '',
  );

}